apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: default-destination-rule
  namespace: default
spec:
  host: '*.default.svc.cluster.local'
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL