apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: disable-mtls-llm
  namespace: default
spec:
  host: llm-service.default.svc.cluster.local
  trafficPolicy:
    tls:
      mode: DISABLE
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: disable-mtls-auth
  namespace: default
spec:
  host: auth-service.default.svc.cluster.local
  trafficPolicy:
    tls:
      mode: DISABLE
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: disable-mtls-ocr
  namespace: default
spec:
  host: ocr-service.default.svc.cluster.local
  trafficPolicy:
    tls:
      mode: DISABLE
